import 'dotenv/config';
import mongoose from 'mongoose';
import { VerseModel, UserModel, BlogPostModel, AnnotationModel, WorkModel } from '@/lib/models';
import { generateEmbedding, generateImage, generateSpeech } from '@/lib/services/openai';
import { upsertVectors } from '@/lib/services/pinecone';

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/rumi';

const rumiVerses = [
  // From Masnavi
  {
    persianText: 'ای陌生人، تو خود را بشناس، خود را، آنجا که عشق آغاز می‌شود، تو را صدا می‌زنند.',
    transliteration: 'Ey gharib, to khod ra beshnas, khod ra, anja ke \'eshq aghaz mishavad, to ra seda mizanand.',
    englishTranslation: 'O stranger, know yourself. Where love begins, there you will be called.',
    summary: 'Rumi speaks of self-knowledge as the pathway to divine love. The journey inward leads to the source of all being.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Self-knowledge', 'Love', 'Divine'],
    wisdomScore: 9,
    complexity: 7,
    emotionalTone: 'contemplative',
    tags: ['wisdom', 'love', 'spiritual', 'journey'],
  },
  {
    persianText: 'آنچه را می‌جویی، تو خودی. از خود بیرون نرو؛ درون خود فرورو و همه چیز را بیاب.',
    transliteration: 'Anjo ra ke juyi, to khodi. Az khod biroon naro; darun khod fururo va hame chiz ra beyaab.',
    englishTranslation: 'What you seek is you yourself. Do not go outside; descend into yourself and find everything.',
    summary: 'Rumi emphasizes that true wisdom lies within us. The search for meaning should be an inward journey.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Self-discovery', 'Inner journey', 'Wisdom'],
    wisdomScore: 10,
    complexity: 6,
    emotionalTone: 'wise',
    tags: ['wisdom', 'spiritual', 'journey', 'inner'],
  },
  {
    persianText: 'بیا تا برایت ببینیم، آنچه ن دیده‌ای و نه شنیده‌ای، نه به خاطر سپرده‌ای.',
    transliteration: 'Bia ta berayat binim, anjo na didei va na shenidi, na be khater separdei.',
    englishTranslation: 'Come, let us see for you what you have not seen, heard, or even imagined.',
    summary: 'Rumi invites the seeker to a transformative experience beyond ordinary perception.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Transformation', 'Divine', 'Spiritual awakening'],
    wisdomScore: 10,
    complexity: 5,
    emotionalTone: 'joyful',
    tags: ['transformation', 'spiritual', 'awakening', 'divine'],
  },
  {
    persianText: 'صوفی برای گندم به بازار رفت، خرید و به خانه آورد. همه دیدند و تعجب کردند.',
    transliteration: 'Soufi bara-ye gandom be bazar raft, kharid va be khaneh avord. Hame didand va ta\'ajjab kardand.',
    englishTranslation: 'The Sufi went to the market to buy wheat, bought it and brought it home. Everyone saw and wondered.',
    summary: 'A humorous tale showing how seekers are often distracted by the very things they seek to transcend.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Wisdom', 'Irony', 'Spiritual journey'],
    wisdomScore: 7,
    complexity: 4,
    emotionalTone: 'humorous',
    tags: ['wisdom', 'irony', 'humor', 'parable'],
  },
  {
    persianText: 'موسیقیِ سُنا را بشنو؛ خاموش می‌ماند اگر کسی نبود که گوش دهد.',
    transliteration: 'Mosighi-ye suna ra beshna; khamush mimanad agar kasi nabud ke goosh darad.',
    englishTranslation: 'Listen to the music of the flute. It would remain silent if there were no one to hear.',
    summary: 'Rumi uses the famous flute metaphor to describe the soul\'s longing and the role of the beloved.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Music', 'Soul', 'Longing', 'Love'],
    wisdomScore: 10,
    complexity: 6,
    emotionalTone: 'melancholic',
    tags: ['music', 'soul', 'longing', 'metaphor'],
  },
  {
    persianText: 'در میانِ ما، حجابی نیست؛ فقط دل‌های ما پرده‌ها را ساخته‌اند.',
    transliteration: 'Dar miyan-e ma, hijab-i nist; faghat del-ha-ye ma pardeha ra sakhteh and.',
    englishTranslation: 'There is no veil between us; only our hearts have made the veils.',
    summary: 'Rumi reveals that the barriers between us and the divine are of our own making.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Illusion', 'Reality', 'Divine'],
    wisdomScore: 10,
    complexity: 6,
    emotionalTone: 'revealing',
    tags: ['illusion', 'reality', 'divine', 'veils'],
  },
  {
    persianText: 'هر که را جان بود، مرگ را ببیند؛ هر که را عشق بود، رستگاری را ببیند.',
    transliteration: 'Har ke ra jan bud, marg ra bebinad; har ke ra \'eshq bud, rästgari ra bebinad.',
    englishTranslation: 'Whoever has life, sees death; whoever has love, sees salvation.',
    summary: 'Rumi connects life, death, love and salvation in a profound philosophical statement.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Life', 'Death', 'Love', 'Salvation'],
    wisdomScore: 10,
    complexity: 5,
    emotionalTone: 'profound',
    tags: ['life', 'death', 'love', 'salvation'],
  },
  // From Divan-e Shams
  {
    persianText: 'در طلبِ وصالِ یار، هر دم بکش جان را، که این نفس، تمامِ هستیِ من است.',
    transliteration: 'Dar talab-e visal-e yar, har dam bokash jan ra, ke in nafas, tamam-e hasti-e man ast.',
    englishTranslation: 'In longing for the beloved, sacrifice your soul each moment, for this breath is the entirety of my existence.',
    summary: 'Rumi expresses the intensity of divine longing, where each breath is an offering to the beloved.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Longing', 'Sufism'],
    wisdomScore: 9,
    complexity: 8,
    emotionalTone: 'passionate',
    tags: ['love', 'passion', 'divine', 'longing'],
  },
  {
    persianText: 'دل را بیازار تا ببینی، آنچه در دل می‌گنجد. در دل، دریایی از نور است.',
    transliteration: 'Del ra biyazar ta bebini, anjo dar del miganjad. Dar del, daryayi az noor ast.',
    englishTranslation: 'Torture your heart so you may see what it contains. In the heart is an ocean of light.',
    summary: 'Rumi speaks of the transformative power of spiritual struggle and the hidden light within.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Spiritual struggle', 'Inner light', 'Transformation'],
    wisdomScore: 9,
    complexity: 7,
    emotionalTone: 'intense',
    tags: ['spiritual', 'transformation', 'light', 'struggle'],
  },
  {
    persianText: 'عشق برده است مرا، بی‌اختیارم، از خود بی‌خودم، در عشق افتاده‌ام.',
    transliteration: 'eshq bordeh ast mara, bi-ikhtiyaram, az khod bi-khodam, dar eshq oftadam.',
    englishTranslation: 'Love has taken me, I am helpless, beside myself with love, I have fallen in love.',
    summary: 'Rumi\'s famous declaration of surrender to divine love.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Surrender', 'Passion'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'passionate',
    tags: ['love', 'surrender', 'passion', 'devotion'],
  },
  {
    persianText: 'ای دوست، بیا که وقت رفتن است؛ این جهان، خوابی بیش نیست.',
    transliteration: 'Ey dust, bia ke vaght raftan ast; in jahan, khabi bish nist.',
    englishTranslation: 'O friend, come, for it is time to go; this world is but a dream.',
    summary: 'Rumi reminds us of life\'s transience and the importance of awakening.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Impermanence', 'Awakening', 'Death'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'urgent',
    tags: ['impermanence', 'awakening', 'world', 'dream'],
  },
  {
    persianText: 'ای پسر، من نورم و تو نوری؛ ما دو روی یک سکه هستیم.',
    transliteration: 'Ey pesar, man nooram va tu noori; ma du roy ye sekke hastim.',
    englishTranslation: 'O son, I am light and you are light; we are two faces of the same coin.',
    summary: 'Rumi reveals the fundamental unity between the seeker and the divine.',
    sourceWork: 'Mawlana Letters',
    philosopher: 'rumi',
    themes: ['Unity', 'Divine', 'Oneness'],
    wisdomScore: 10,
    complexity: 3,
    emotionalTone: 'loving',
    tags: ['unity', 'divine', 'oneness', 'love'],
  },
  // Additional verses
  {
    persianText: 'خواجه شد و خوابید؛ درویش بمُرد و زنده شد. این است کار عشق.',
    transliteration: 'Khwajeh shod va khabid; darvish bemord va zendeh shod. In ast kar-e \'eshq.',
    englishTranslation: 'The master fell asleep and the dervish died and came to life. This is the work of love.',
    summary: 'Love transforms us completely, making us die to our old selves and be reborn.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Transformation', 'Love', 'Death'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'mysterious',
    tags: ['transformation', 'love', 'rebirth'],
  },
  {
    persianText: 'هیچ دروازه‌ای بسته نیست برای کسی که واقعاً می‌خواهد وارد شود.',
    transliteration: 'Hich darvazeye basti nist bara-ye kasi ke vaghe\'an mikhvad vared shavad.',
    englishTranslation: 'No door is closed for those who truly wish to enter.',
    summary: 'The path to the divine is always open to the sincere seeker.',
    sourceWork: 'Fihi Ma Fihi',
    philosopher: 'rumi',
    themes: ['Divine', 'Spiritual journey', 'Openness'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'hopeful',
    tags: ['divine', 'journey', 'openness'],
  },
  {
    persianText: 'عشق، زبانی است که همه می‌فهمند، اما فقط عشق می‌تواند بگوید.',
    transliteration: 'eshq, zabani ast ke hameh mimanand, vali faqat eshq mitavanad begohad.',
    englishTranslation: 'Love is a language that everyone understands, but only love can speak.',
    summary: 'Love is the universal language that transcends words and connects souls.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Communication', 'Unity'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['love', 'language', 'unity'],
  },
  {
    persianText: 'زخم را نشان بده تا ببینم؛ جایی که نور وارد می‌شود، همان جاست.',
    transliteration: 'Zakhme ra neshan bedeh ta bebini; jayi ke noor vared mishavad, hamun jast.',
    englishTranslation: 'Show me your wound, that I may see; where the light enters, that is where.',
    summary: 'Our wounds and struggles become the vessels for divine light.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Transformation', 'Light', 'Struggle'],
    wisdomScore: 10,
    complexity: 5,
    emotionalTone: 'compassionate',
    tags: ['wound', 'light', 'transformation'],
  },
  {
    persianText: 'صدای ناقوس را بشنو، نه با گوش، بلکه با قلب.',
    transliteration: 'Sedaye naghous ra beshna, na ba goosh, Balkeh ba del.',
    englishTranslation: 'Listen to the bells, not with your ears, but with your heart.',
    summary: 'True spiritual hearing is through the heart, not the physical ears.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Spiritual hearing', 'Heart', 'Awareness'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'contemplative',
    tags: ['heart', 'awareness', 'spiritual'],
  },
  {
    persianText: 'وقتی عشق می‌آید، خرد خواب می‌بیند.',
    transliteration: 'Vaqt ke \'eshq miyad, kherad khab mibinad.',
    englishTranslation: 'When love comes, reason falls asleep.',
    summary: 'Divine love transcends rational thought and awakens the soul.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Reason', 'Awakening'],
    wisdomScore: 9,
    complexity: 3,
    emotionalTone: 'mystical',
    tags: ['love', 'reason', 'awakening'],
  },
  {
    persianText: 'هیچ چیز از دست نداده‌ای، مگر آنچه را که هرگز نداشتی.',
    transliteration: 'Hich chiz az dast nadadei, magar anjo ke hargiz nadashti.',
    englishTranslation: 'You have lost nothing except what you never had.',
    summary: 'Material attachments were never truly ours; only the divine is permanent.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Non-attachment', 'Loss', 'Divine'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'liberating',
    tags: ['non-attachment', 'loss', 'wisdom'],
  },
  {
    persianText: 'عشق، خانه را ویران می‌کند و با خاک، قصر می‌سازد.',
    transliteration: 'eshq, khaneh ra viran mikunad va ba khak, ghasr misazad.',
    englishTranslation: 'Love destroys the house and with its dust builds a palace.',
    summary: 'Love breaks down our ego to rebuild us as something greater.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Destruction', 'Rebuilding'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'transformative',
    tags: ['love', 'destruction', 'rebirth'],
  },
];

const hafezVerses = [
  {
    persianText: 'ای صبا！نَفَسی زِ رُواقِ مِهرِackbar برسانم، که میلِ مُلَک‌السَّلطَنَت روزی نِهادست.',
    transliteration: 'Ey Saba! Nafas-i az rowaq-e mehr bar resanam, ke mil-e malk-ol-saltanat ruzi nehadst.',
    englishTranslation: 'O morning breeze! Carry a breath from the sphere of love to the king, for destiny has ordained it.',
    summary: 'Hafez speaks of destiny and the divine order of the universe, using the metaphor of the wind carrying messages.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Destiny', 'Divine', 'Love'],
    wisdomScore: 9,
    complexity: 7,
    emotionalTone: 'mystical',
    tags: ['destiny', 'divine', 'mystical'],
  },
  {
    persianText: 'اگر آن ترکِ شیرازی بِهَدَست آوردِدلِ ما را، ببرد از کف ما طوطیِ هندیِ زبان‌بست را.',
    transliteration: 'Agar an Turk-e Shirazi be dast avord del-e ma ra, bebar az kaf-e ma tuti-ye Hindi-ye zaban bast ra.',
    englishTranslation: 'If that Turkish beauty from Shiraz takes our heart in hand, she would take from our hands even the speechless parrot of India.',
    summary: 'Hafez uses the famous parrot metaphor to express how love makes us speechless and devoted.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Love', 'Devotion', 'Beauty'],
    wisdomScore: 9,
    complexity: 6,
    emotionalTone: 'passionate',
    tags: ['love', 'devotion', 'beauty'],
  },
  {
    persianText: 'مَیِ خُور که گِرَدَرِ مِیخانه بَدَرَد، بَندَه بُرد زَکات، پیشِ درِ مِیخانه بِرَو.',
    transliteration: 'May-e khor ke gerdar-e meykhaneh bedarad, bande bord zakat, pish-e dar-e meykhaneh berow.',
    englishTranslation: 'Drink wine, for the one who empties the wine-cellar brings the beggar to pay tribute. Go to the door of the tavern.',
    summary: 'Hafez celebrates the spiritual liberation found in the wine of divine love, even as religious authorities condemn it.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Liberation', 'Divine love', 'Spiritual freedom'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'defiant',
    tags: ['liberation', 'divine', 'freedom'],
  },
  {
    persianText: 'خواجِہ شمس‌الدین محمد حافظِ شیرازی، مَن کَهَستم؟',
    transliteration: 'Khwajeh Shams-e Din Muhammad Hafez-e Shirazi, man keh astam?',
    englishTranslation: 'Khwajeh Shams-e Din Muhammad Hafez of Shiraz, who am I?',
    summary: 'Hafez poses the ultimate question of self-identity, a central theme in mystical poetry.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Self-knowledge', 'Identity', 'Mysticism'],
    wisdomScore: 10,
    complexity: 3,
    emotionalTone: 'contemplative',
    tags: ['self', 'identity', 'mysticism'],
  },
  {
    persianText: 'دَرمیانِ رَه، اگرچه بُرداری، بِه سَربلَندی مِرو، که روزی، همین رَه، بَرَت خواهد کشید.',
    transliteration: 'Dar miyan-e rah, agar chi bordari, be sar-bolandi moro, ke ruzi, hamin rah, barat khashad keshid.',
    englishTranslation: 'On the way, though you carry a burden, walk with head held high, for one day, this very path will long for you.',
    summary: 'Hafez reminds us that our struggles now will be missed when they are gone - value the journey.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Journey', 'Perseverance', 'Wisdom'],
    wisdomScore: 9,
    complexity: 6,
    emotionalTone: 'wise',
    tags: ['journey', 'wisdom', 'perseverance'],
  },
];

const saadiVerses = [
  {
    persianText: 'انسان را بباید که از خویشتن بِرهَد، که هر که در خویشتن ماند، به جایی نرسد.',
    transliteration: 'Insan ra babayad ke az khishtun berahad, har ke dar khishtun mand, be jayi naresad.',
    englishTranslation: 'One must escape from oneself, for whoever remains within themselves will never reach anywhere.',
    summary: 'Saadi teaches that self-limiting beliefs must be transcended to grow spiritually.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Self-transcendence', 'Growth', 'Wisdom'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['wisdom', 'growth', 'self'],
  },
  {
    persianText: 'دوستِ واقعی در روزِ سخت شناخته می‌شود.',
    transliteration: 'Doust-e vagheyi dar roz-e sakht shenakhte mishavad.',
    englishTranslation: 'A true friend is known in difficult times.',
    summary: "Saadi's famous saying about the nature of true friendship.",
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Friendship', 'Loyalty', 'Wisdom'],
    wisdomScore: 8,
    complexity: 3,
    emotionalTone: 'wise',
    tags: ['friendship', 'loyalty', 'wisdom'],
  },
  {
    persianText: 'سخنِ نیکو را بِه هر زبانی که بگویی، بهار است.',
    transliteration: 'Sokhan-e nigo ra be har zaban-i ke beguyi, bahar ast.',
    englishTranslation: 'Good words are spring in any language.',
    summary: 'Saadi celebrates the universal power of kind and wise speech.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Speech', 'Wisdom', 'Kindness'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'hopeful',
    tags: ['speech', 'wisdom', 'kindness'],
  },
  {
    persianText: 'کسی که درختِ صبر بکارد، میوۀ آن را در بهارِ زندگی می‌چیند.',
    transliteration: 'Kasi ke derakht-e sabr bokarad, miveh an ra dar bahar-e zandegi michinad.',
    englishTranslation: 'One who plants the tree of patience will harvest its fruit in the spring of life.',
    summary: 'Saadi teaches that patience and perseverance lead to rewards in life.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Patience', 'Perseverance', 'Reward'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'hopeful',
    tags: ['patience', 'perseverance', 'wisdom'],
  },
  {
    persianText: 'با درویشانِ نازنین، نازنین باش؛ که گنجِ عزیز، در خاکِ خواری است.',
    transliteration: 'Ba darvishan-e naznin, naznin bash; ke ganj-e aziz, dar khak-e kharist.',
    englishTranslation: 'Be gentle with the noble poor, for precious treasure lies in humble dust.',
    summary: 'Saadi reminds us that true worth is not measured by wealth or دل.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Humility', 'Wisdom', 'Inner worth'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['humility', 'wisdom', 'worth'],
  },
];

const attarVerses = [
  {
    persianText: 'پرندهِ seeker است که در پَروازِ خویشتن، آشیان را جستجو می‌کند.',
    transliteration: 'Parandeh-ye seeker ast ke dar parvaz-e khishtun, ashiran ra jostojo mikunad.',
    englishTranslation: 'The seeker is the bird that, in its flight, searches for its nest.',
    summary: 'Attar uses the bird metaphor to describe the soul\'s search for its true home in the divine.',
    sourceWork: 'Conference of the Birds',
    philosopher: 'attar',
    themes: ['Seeking', 'Journey', 'Soul'],
    wisdomScore: 9,
    complexity: 6,
    emotionalTone: 'mystical',
    tags: ['seeking', 'journey', 'soul'],
  },
  {
    persianText: 'هر که را جان بُوَد، مرگ را ببیند؛ هر که را عشق بُوَد، رهایی را ببیند.',
    transliteration: 'Har ke ra jan bowad, marg ra bebinad; har ke ra eshq bowad, rahayi ra bebinad.',
    englishTranslation: 'Whoever has life will see death; whoever has love will see liberation.',
    summary: 'Attar connects the themes of life, death, and love in a mystical statement.',
    sourceWork: 'Ilahi-Nama',
    philosopher: 'attar',
    themes: ['Life', 'Death', 'Love', 'Liberation'],
    wisdomScore: 10,
    complexity: 5,
    emotionalTone: 'mystical',
    tags: ['life', 'death', 'love', 'liberation'],
  },
  {
    persianText: 'زیرِ پایِ صوفی، گنجِ پنهان است.',
    transliteration: 'Zir-e pay-e soufi, ganj-e penhan ast.',
    englishTranslation: 'Beneath the dervish\'s feet lies hidden treasure.',
    summary: 'Attar teaches that wisdom is found in the humblest of places.',
    sourceWork: 'Tazkirat al-Awliya',
    philosopher: 'attar',
    themes: ['Humility', 'Wisdom', 'Hidden truth'],
    wisdomScore: 8,
    complexity: 3,
    emotionalTone: 'wise',
    tags: ['humility', 'wisdom', 'truth'],
  },
];

const sanaiVerses = [
  {
    persianText: 'ای خواجه، اگر می‌خواهی که جانت را بِستانی، باید که خویشتن را فروگذاری.',
    transliteration: 'Ey khwajeh, agar mikhahi ke janat ra bestani, bayad ke khishtun ra foroghari.',
    englishTranslation: 'O master, if you wish to save your soul, you must abandon yourself.',
    summary: 'Sanai teaches that self-surrender is the path to spiritual salvation.',
    sourceWork: 'Walled Garden of Truth',
    philosopher: 'sanai',
    themes: ['Surrender', 'Selflessness', 'Salvation'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['surrender', 'selflessness', 'salvation'],
  },
  {
    persianText: 'عشق، نردبانِ آسمان است؛ بی‌عشق، زمین هم بر تو تنگ است.',
    transliteration: 'eshq, nardaban-e asman ast; bi-eshq, zamin ham bar oy tang ast.',
    englishTranslation: 'Love is the ladder to heaven; without love, even the earth is narrow to you.',
    summary: 'Sanai uses the ladder metaphor to show that love is the path to transcendence.',
    sourceWork: 'Walled Garden of Truth',
    philosopher: 'sanai',
    themes: ['Love', 'Transcendence', 'Spiritual path'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['love', 'transcendence', 'path'],
  },
  {
    persianText: 'هر دلی که عشق را نشناخت، سنگ است و سنگ بماند.',
    transliteration: 'Har del ke eshq ra nashnakht, sang ast va sang bemanad.',
    englishTranslation: 'Any heart that does not know love is stone, and stone remains stone.',
    summary: 'Sanai teaches that love is what gives life and meaning to the heart.',
    sourceWork: 'Walled Garden of Truth',
    philosopher: 'sanai',
    themes: ['Love', 'Heart', 'Life'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['love', 'heart', 'life'],
  },
  // Additional Rumi verses
  {
    persianText: 'تو آنی که می‌جویی؛ تو همانی که می‌یابی.',
    transliteration: 'To ani ke mijuyi; to haman-i ke miyabi.',
    englishTranslation: 'You are the one you seek; you are the same one you find.',
    summary: 'Rumi teaches that the divine exists within us - we are not separate from what we seek.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Self-knowledge', 'Divine', 'Unity'],
    wisdomScore: 10,
    complexity: 3,
    emotionalTone: 'revealing',
    tags: ['self', 'divine', 'unity'],
  },
  {
    persianText: 'عشق، همه چیز را می‌شوید؛ عشق، همه چیز را نو می‌کند.',
    transliteration: 'eshq, hame chiz ra mishuyad; eshq, hame chiz ra no mikunad.',
    englishTranslation: 'Love washes everything; love makes everything new.',
    summary: 'Rumi celebrates the transformative power of love that purifies and renews.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Transformation', 'Renewal'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'joyful',
    tags: ['love', 'transformation', 'renewal'],
  },
  {
    persianText: 'در خُمارِ عشق، مستِ بی‌خَودَم؛ این مستی، اَفْقَرِ دل است.',
    transliteration: 'Dar khamar-e eshq, mast-e bi-khodam; in masti, afzar-e jah ast.',
    englishTranslation: 'In the wine of love, I am drunk and beside myself; this intoxication is richer than all worldly دل.',
    summary: 'Rumi values spiritual intoxication over worldly achievements.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Spiritual intoxication', 'Worldly vs spiritual'],
    wisdomScore: 9,
    complexity: 6,
    emotionalTone: 'passionate',
    tags: ['love', 'intoxication', 'spiritual'],
  },
  {
    persianText: 'مُ<ctrl46>ایِ رُوَح را بِخُور که جهان را بَهُجَت می‌دهد.',
    transliteration: 'May-e ruh ra bikhur ke jahan ra behjat midahad.',
    englishTranslation: 'Drink the wine of the spirit, for it gives joy to the world.',
    summary: 'The divine spirit brings joy to all existence.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Spirit', 'Joy', 'Divine'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'joyful',
    tags: ['spirit', 'joy', 'divine'],
  },
  {
    persianText: 'صَحبَتِ یار، از هزار دَفْتَرِ عِلْم بهتر است.',
    transliteration: 'Sahabat-e yar, az hezar daftar-e elm behtare ast.',
    englishTranslation: 'The companionship of the beloved is better than a thousand books of knowledge.',
    summary: 'Direct spiritual experience outweighs mere academic learning.',
    sourceWork: 'Fihi Ma Fihi',
    philosopher: 'rumi',
    themes: ['Spiritual experience', 'Knowledge', 'Love'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['experience', 'knowledge', 'love'],
  },
  {
    persianText: 'هر نَفْسی که بیدار شد، روزیِ روشن دارد.',
    transliteration: 'Har nafas-i ke biyar shod, ruzi-ye roshan darad.',
    englishTranslation: 'Every soul that awakens has a bright day ahead.',
    summary: 'Spiritual awakening brings illumination and hope.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Awakening', 'Hope', 'Light'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'hopeful',
    tags: ['awakening', 'hope', 'light'],
  },
  {
    persianText: 'ای دل، از غصه بِرَه؛ هر که بمیرد، به بهشت رود.',
    transliteration: 'Ey del, az ghasra bara; har ke bemirad, be behest ravad.',
    englishTranslation: 'O heart, free yourself from sorrow; whoever dies shall go to heaven.',
    summary: 'Release attachment to worldly sorrow - death brings spiritual liberation.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Liberation', 'Death', 'Heaven'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'liberating',
    tags: ['liberation', 'death', 'heaven'],
  },
  {
    persianText: 'چون آفتاب برآیی، سایه نیست؛ چون عشق درآیی، نَفس نیست.',
    transliteration: 'Con asrtab barvari, saye nist; con eshq darvari, nafas nist.',
    englishTranslation: 'When you rise like the sun, there is no shadow; when love enters, there is no breath (ego).',
    summary: 'Divine love eliminates all obstacles and the ego.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Divine', 'Ego death'],
    wisdomScore: 10,
    complexity: 6,
    emotionalTone: 'transformative',
    tags: ['love', 'divine', 'ego'],
  },
  {
    persianText: 'مومِ دل را نزد شمع نگه دار؛ که عشق، همه را آب می‌کند.',
    transliteration: 'Mum-e del ra nazd-e shamsh negah dar; ke eshq, hame ra ab mikunad.',
    englishTranslation: 'Keep the wax of your heart near the candle; for love melts everything.',
    summary: 'The heart must be close to divine light, which love melts and transforms.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Heart', 'Divine light', 'Love'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['heart', 'light', 'love'],
  },
  {
    persianText: 'صبر کن، صبر کن، صبر کن؛ آنچه می‌خواهی، می‌رسد.',
    transliteration: 'Sabar kon, sabar kon, sabar kon; anjo mikhvari, mirasad.',
    englishTranslation: 'Be patient, be patient, be patient; what you desire will come.',
    summary: 'Patience brings the fulfillment of desires in divine timing.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Patience', 'Divine timing', 'Hope'],
    wisdomScore: 8,
    complexity: 3,
    emotionalTone: 'hopeful',
    tags: ['patience', 'timing', 'hope'],
  },
  {
    persianText: 'ای پُرندۀ مِهر، آشیانۀ خویشتن بشناس.',
    transliteration: 'Ey parvandeh-ye mehr, ashianeh-ye khishtun beshnas.',
    englishTranslation: 'O bird of love, recognize your own nest.',
    summary: 'The soul must recognize its true home in the divine.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Soul', 'Home', 'Love'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'contemplative',
    tags: ['soul', 'home', 'love'],
  },
  {
    persianText: 'بی‌مِهر، جهانِ تاریکِ دل است؛ با مِهر، هر جا بهشت است.',
    transliteration: 'Bi-mehr, jahan-e tarik-e jah ast; ba-mehr, har ja behest ast.',
    englishTranslation: 'Without love, the world is dark and worldly; with love, everywhere is heaven.',
    summary: 'Love transforms any circumstance into paradise.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Paradise', 'Transformation'],
    wisdomScore: 10,
    complexity: 5,
    emotionalTone: 'transformative',
    tags: ['love', 'paradise', 'transformation'],
  },
  {
    persianText: 'از خُویش بِگُذْر تا بِه خداوَندِ رِسی.',
    transliteration: 'Az khuysh begzar ta be Khodavand rest.',
    englishTranslation: 'Transcend yourself to reach God.',
    summary: 'Self-transcendence is the path to the divine.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Transcendence', 'Divine', 'Path'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['transcendence', 'divine', 'path'],
  },
  {
    persianText: 'چشمِ بسته، همه چیز درِ بسته؛ چشمِ باز، همه چیز درِ باز.',
    transliteration: 'cheshm-e bast, hame chiz dar-e bast; cheshb-e baz, hame chiz dar-e baz.',
    englishTranslation: 'Closed eyes, everything is closed; open eyes, everything is open.',
    summary: 'Our perception determines our experience of reality.',
    sourceWork: 'Fihi Ma Fihi',
    philosopher: 'rumi',
    themes: ['Perception', 'Reality', 'Awareness'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'contemplative',
    tags: ['perception', 'reality', 'awareness'],
  },
  {
    persianText: 'عشق، زبانِ بی‌زبانِ زبان است.',
    transliteration: 'eshq, zabane bi-zabane zaban ast.',
    englishTranslation: 'Love is the language beyond language.',
    summary: 'Love communicates what words cannot express.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Communication', 'Mystical'],
    wisdomScore: 9,
    complexity: 3,
    emotionalTone: 'mystical',
    tags: ['love', 'communication', 'mystical'],
  },
  {
    persianText: 'آن کس که جان دارد، بمیرد؛ آن کس که عشق دارد، زنده است.',
    transliteration: 'An kas ke jan darad, bemirad; an kas ke eshq darad, zande ast.',
    englishTranslation: 'One who has (worldly) life will die; one who has love is alive.',
    summary: 'True life is found in love, not in mere existence.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Life', 'Love', 'Death'],
    wisdomScore: 10,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['life', 'love', 'death'],
  },
  {
    persianText: 'درِ باز، نویدِ فَرَََوست؛ درِ بسته، بُهتاست.',
    transliteration: 'Dar-e baz, navid-e firoozeh; dar-e bast, boht ast.',
    englishTranslation: 'Open door is a promise of treasure; closed door is sorrow.',
    summary: 'Openness to the divine brings blessings; closure brings sorrow.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Openness', 'Divine', 'Blessing'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['openness', 'divine', 'blessing'],
  },
  {
    persianText: 'ای نورِ دیده، روشنِ بینِ دل؛ بی‌تو، تاریکیِ جاودان است.',
    transliteration: 'Ey noor-e dida, roshan-e bin-e jah; bi-to, tariki-ye javdan ast.',
    englishTranslation: 'O light of sight, the illuminator of worldly sight; without you, there is eternal darkness.',
    summary: 'The divine light is necessary for true vision.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Divine light', 'Vision', 'Darkness'],
    wisdomScore: 9,
    complexity: 6,
    emotionalTone: 'mystical',
    tags: ['light', 'vision', 'darkness'],
  },
  {
    persianText: 'خُویشتن را بشکَن تا خُداوَند را بیابی.',
    transliteration: 'Khishtun ra beshkan ta Khodavand ra beyaabi.',
    englishTranslation: 'Break yourself to find God.',
    summary: 'Ego must be shattered to find the divine.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Ego death', 'Divine', 'Transformation'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'transformative',
    tags: ['ego', 'divine', 'transformation'],
  },
  {
    persianText: 'آبِ دُریا را نتوان چشید؛ لیکن، تشنگیِ ما را ببرد.',
    transliteration: 'Ab-e darya ra netavan chashid; lekin, tashnaghi-ye ma ra bebarad.',
    englishTranslation: "One cannot taste the ocean's water; yet it takes away our thirst.",
    summary: 'The divine satisfies the deepest longing of the soul.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Divine', 'Satisfaction', 'Longing'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'satisfying',
    tags: ['divine', 'satisfaction', 'longing'],
  },
  {
    persianText: 'مِیخور که رَقَم، کُلِّ دل فَرو ریزد.',
    transliteration: 'May khor ke raqam, kolli-ye jah furo rizad.',
    englishTranslation: 'Drink wine, for it will pour down the entire world.',
    summary: 'Divine intoxication overwhelms the material world.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Intoxication', 'Divine', 'World'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'intoxicated',
    tags: ['intoxication', 'divine', 'world'],
  },
  {
    persianText: 'عاشق، بیدارِ دل بیدار است.',
    transliteration: 'Ashaq, biyara-e jah biyara ast.',
    englishTranslation: 'The lover is awake to the awake world (beyond material).',
    summary: 'The lover perceives a higher reality.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Awareness', 'Higher reality'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'awake',
    tags: ['love', 'awareness', 'reality'],
  },
  {
    persianText: 'هر که را عشق بُوَد، از دل رَهَد.',
    transliteration: 'Har ke ra eshq bowad, az jah rahad.',
    englishTranslation: 'Whoever has love escapes from the world.',
    summary: 'Love liberates from worldly attachment.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Liberation', 'World'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'liberating',
    tags: ['love', 'liberation', 'world'],
  },
  {
    persianText: 'دلِ بیدار، چشمِ بیدار است.',
    transliteration: 'Del-e biyara, chashm-e biyara ast.',
    englishTranslation: 'An awake heart is an awake eye.',
    summary: 'Spiritual awakening opens inner vision.',
    sourceWork: 'Fihi Ma Fihi',
    philosopher: 'rumi',
    themes: ['Awakening', 'Heart', 'Vision'],
    wisdomScore: 9,
    complexity: 3,
    emotionalTone: 'wise',
    tags: ['awakening', 'heart', 'vision'],
  },
  {
    persianText: 'در کوچه‌های عشق، هر که بیفتد، برخیزد.',
    transliteration: 'Dar kucheh-ye eshq, har ke bioftad, barkhizad.',
    englishTranslation: 'In the alley of love, whoever falls will rise.',
    summary: 'Love gives the strength to rise after any fall.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Love', 'Resilience', 'Rise'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'hopeful',
    tags: ['love', 'resilience', 'hope'],
  },
  {
    persianText: 'بی‌عشق، زندگی، مرگِ دل است.',
    transliteration: 'Bi-eshq, zandegi, marg-e jah ast.',
    englishTranslation: 'Without love, life is death of the world.',
    summary: 'Life without love is spiritual death.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Life', 'Death'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'serious',
    tags: ['love', 'life', 'death'],
  },
  {
    persianText: 'عشق، آتشِ بی‌دود است که سوزد و نسوزد.',
    transliteration: 'eshq, atash-e bi-dud ast ke suzad va na-suzad.',
    englishTranslation: 'Love is fire without smoke that burns but does not consume.',
    summary: 'Divine love transforms without destroying.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Love', 'Fire', 'Transformation'],
    wisdomScore: 10,
    complexity: 5,
    emotionalTone: 'mystical',
    tags: ['love', 'fire', 'transformation'],
  },
  {
    persianText: 'سفرِ هزار میل، از یک قَدَم آغاز می‌شود.',
    transliteration: 'Safar-e hezar mil, az yek ghadam aghaz mishavad.',
    englishTranslation: 'A journey of a thousand miles begins with a single step.',
    summary: 'The spiritual path begins with one small step.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Journey', 'Beginnings', 'Path'],
    wisdomScore: 9,
    complexity: 3,
    emotionalTone: 'wise',
    tags: ['journey', 'beginnings', 'path'],
  },
  {
    persianText: 'ای دل، دل به بِه= دل بِه= تو چیست؟',
    transliteration: 'Ey jah, jah beh to chi st?',
    englishTranslation: 'O world, what are you to one who has the Beloved?',
    summary: 'When we have the divine, worldly things become meaningless.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['World', 'Divine', 'Detachment'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'detached',
    tags: ['world', 'divine', 'detachment'],
  },
  {
    persianText: 'مُومِ خویشتن را پیشِ آفتاب بَر',
    transliteration: 'Mum-e khishtun ra pish-e asrtab bar.',
    englishTranslation: 'Bring your wax (heart) before the sun.',
    summary: 'Offer the heart to divine light for transformation.',
    sourceWork: 'Masnavi',
    philosopher: 'rumi',
    themes: ['Heart', 'Divine light', 'Transformation'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['heart', 'light', 'transformation'],
  },
  {
    persianText: 'خوابِ بیداری، بهتر از بیداریِ خواب است.',
    transliteration: 'Khab-e biyari, behtar az biyari-ye khab ast.',
    englishTranslation: 'The sleep of awareness is better than the awakening of sleep.',
    summary: 'True spiritual sleep (rest in God) is better than false awakening.',
    sourceWork: 'Fihi Ma Fihi',
    philosopher: 'rumi',
    themes: ['Awareness', 'Sleep', 'Spiritual'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'paradoxical',
    tags: ['awareness', 'sleep', 'spiritual'],
  },
  {
    persianText: 'رازِ بزرگ، در سینهٔ کوچک می‌گنجد.',
    transliteration: 'Raz-e bozorg, dar sineh-ye kuchak miganjad.',
    englishTranslation: 'The great mystery fits in a small heart.',
    summary: 'The infinite divine resides in the humble heart.',
    sourceWork: 'Divan-e Shams',
    philosopher: 'rumi',
    themes: ['Mystery', 'Heart', 'Divine'],
    wisdomScore: 10,
    complexity: 4,
    emotionalTone: 'mystical',
    tags: ['mystery', 'heart', 'divine'],
  },
];

// Additional Hafez verses
const hafezVersesAdditional = [
  {
    persianText: 'در سرایِ مِهر، هر که بُوَد، شاه است.',
    transliteration: 'Dar saray-e mehr, har ke bowad, shah ast.',
    englishTranslation: 'In the house of love, whoever exists is a king.',
    summary: 'Love makes everyone noble and royal.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Love', 'Nobility', 'Kingship'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'noble',
    tags: ['love', 'nobility', 'royal'],
  },
  {
    persianText: 'ساقی، بیا که وقتِ طرب رسید.',
    transliteration: 'Saqi, bia ke vaqt-e tarab resid.',
    englishTranslation: 'O cupbearer, come, for the time of joy has arrived.',
    summary: 'The time for divine joy has come.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Joy', 'Wine', 'Celebration'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'joyful',
    tags: ['joy', 'wine', 'celebration'],
  },
  {
    persianText: 'عیشِ مُستمر، در سایهٔ مِهرِ یار است.',
    transliteration: 'Eysh-e mostamar, dar saye-ye mehr-e yar ast.',
    englishTranslation: 'Eternal bliss is in the shade of the beloved\'s love.',
    summary: 'True happiness is found in love.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Bliss', 'Love', 'Happiness'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'blissful',
    tags: ['bliss', 'love', 'happiness'],
  },
  {
    persianText: 'مِی و مُستی و معشوق و مَیدان، همه چهارگانهٔ عشق است.',
    transliteration: 'May o masti o ma\'shuq o meydan, chahar ganeh-ye eshq ast.',
    englishTranslation: 'Wine, intoxication, beloved, and arena - all four are the aspects of love.',
    summary: 'Love encompasses all these dimensions.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Love', 'Wine', 'Intoxication'],
    wisdomScore: 9,
    complexity: 6,
    emotionalTone: 'mystical',
    tags: ['love', 'wine', 'intoxication'],
  },
  {
    persianText: 'هر که را در این بازارِ کُهن بُوَد، دِلَُّده بُوَد.',
    transliteration: 'Har ke ra dar in bazar-e kuhan bowad, del-dahde bowad.',
    englishTranslation: 'Whoever has a heart in this ancient bazaar is blessed.',
    summary: 'Those with hearts in the spiritual market are fortunate.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Heart', 'Spiritual', 'Blessing'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'blessed',
    tags: ['heart', 'spiritual', 'blessing'],
  },
  {
    persianText: 'از مِیخانه سخنِ تازه مِی‌آید.',
    transliteration: 'Az meykhaneh sokhan-e tazeh mi-ayad.',
    englishTranslation: 'New words come from the wine-cellar.',
    summary: 'Divine inspiration flows from spiritual places.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Inspiration', 'Divine', 'Wisdom'],
    wisdomScore: 8,
    complexity: 4,
    inspirational: true,
    tags: ['inspiration', 'divine', 'wisdom'],
  },
  {
    persianText: 'حالِ ما، در چنگالِ نَظَرِ یار است.',
    transliteration: 'Hal-e ma, dar changal-e nazar-e yar ast.',
    englishTranslation: 'Our state is in the gaze of the beloved.',
    summary: 'Our spiritual state depends on the beloved\'s attention.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Divine', 'Fate', 'Love'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'contemplative',
    tags: ['divine', 'fate', 'love'],
  },
  {
    persianText: 'از دیده بیرون کن، تا بُوَد که در دل بِنای.',
    transliteration: 'Az dida birun kon, tu bowad ke dar del banay.',
    englishTranslation: 'Remove from sight, so that it may be built in the heart.',
    summary: 'What we let go of externally becomes internal.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Heart', 'Inner', 'Transformation'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['heart', 'inner', 'transformation'],
  },
  {
    persianText: 'صَبر کن، که بهارِ جاودان خواهد آمد.',
    transliteration: 'Sabar kon, ke bahar-e javdan khad avad.',
    englishTranslation: 'Be patient, for the eternal spring will come.',
    summary: 'Patience brings eternal spring.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Patience', 'Spring', 'Eternity'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'hopeful',
    tags: ['patience', 'spring', 'eternity'],
  },
  {
    persianText: 'مِیِ ناب، روح را صَفو می‌دهد.',
    transliteration: 'May-e nab, ruh ra safo midahad.',
    englishTranslation: 'Pure wine purifies the soul.',
    summary: 'Divine wine purifies the spiritual nature.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Purification', 'Soul', 'Wine'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'purifying',
    tags: ['purification', 'soul', 'wine'],
  },
  {
    persianText: 'عشق، سَرِ دل را به خاک می‌زند.',
    transliteration: 'eshq, sar-e jah ra be khak mizanad.',
    englishTranslation: 'Love strikes the head of the world to the ground.',
    summary: 'Love humbles the mighty.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Love', 'Humility', 'Power'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'powerful',
    tags: ['love', 'humility', 'power'],
  },
  {
    persianText: 'ای دلِ بی‌کس، کُسی نیست که نِیست.',
    transliteration: 'Ey jah-e bi-kas, kasi nist ke nist.',
    englishTranslation: 'O world of the helpless, no one is who is not.',
    summary: 'In the material world, no one truly exists without the divine.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['World', 'Divine', 'Existence'],
    wisdomScore: 9,
    complexity: 6,
    emotionalTone: 'philosophical',
    tags: ['world', 'divine', 'existence'],
  },
  {
    persianText: 'برو، که کارِ ما با نَظَرِ سلطان بُوَد.',
    transliteration: 'Boru, ke kar-e ma ba nazar-e soltane bowad.',
    englishTranslation: 'Go, for our affair is with the Sultan\'s gaze.',
    summary: 'Our fate rests with the divine.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Fate', 'Divine', 'Sultan'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'fateful',
    tags: ['fate', 'divine', 'sultan'],
  },
  {
    persianText: 'دُرِ مِهر، در مَحالِ نیست.',
    transliteration: 'Dorr-e mehr, dar mahall-e nist.',
    englishTranslation: 'The pearl of love is not in this place.',
    summary: 'True love is not found in this world.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Love', 'Pearl', 'Otherworldly'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'mystical',
    tags: ['love', 'pearl', 'mystical'],
  },
  {
    persianText: 'بیدارِ دل بیدار است و خوابِ عشق، خواب.',
    transliteration: 'Biyar-e jah biyar ast va khab-e eshq, khab.',
    englishTranslation: 'The awake worldly are awake; the sleep of love is sleep.',
    summary: 'Worldly awakening is false; spiritual sleep is true rest.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Awakening', 'Sleep', 'Love'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'paradoxical',
    tags: ['awakening', 'sleep', 'love'],
  },
  {
    persianText: 'حالِ خوب، از نَظَرِ خوب بُوَد.',
    transliteration: 'Hal-e khub, az nazar-e khub bowad.',
    englishTranslation: 'Good state comes from good observation.',
    summary: 'Our perspective shapes our experience.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Perspective', 'State', 'Vision'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['perspective', 'state', 'vision'],
  },
  {
    persianText: 'مِی سازد و مُستی کُشد؛ این، کارِ عشق است.',
    transliteration: 'May sazad va masti kushad; in, kar-e eshq ast.',
    englishTranslation: 'Wine makes and intoxication kills; this is the work of love.',
    summary: 'Love both creates and destroys.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Love', 'Creation', 'Destruction'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'powerful',
    tags: ['love', 'creation', 'destruction'],
  },
  {
    persianText: 'گنج در خانهٔ فقیر بُوَد، اگر دَستِ دولت بَرَد.',
    transliteration: 'Ganj dar khaneh-ye faqir bowad, agar dast-e dolat barad.',
    englishTranslation: 'Treasure is in the poor house, if the hand of fortune reaches.',
    summary: 'True wealth can be found in humble places.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Treasure', 'Fortune', 'Humility'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['treasure', 'fortune', 'humility'],
  },
  {
    persianText: 'چون سرو، به بِه= دل بِه= رُوِ دل رَوَی',
    transliteration: 'Con sarv, be ro-ye jah ravay.',
    englishTranslation: 'Like the cypress, walk with head high before the world.',
    summary: 'Maintain dignity in the face of worldly challenges.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Dignity', 'World', 'Cypress'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'dignified',
    tags: ['dignity', 'world', 'cypress'],
  },
  {
    persianText: 'یار، همین جا بُوَد؛ لیکن، نِیست نمای.',
    transliteration: 'Yar, hamin ja bowad; lekin, nist nimay.',
    englishTranslation: 'The beloved is right here; but do not see as non-existent.',
    summary: 'The divine surrounds us, but we fail to perceive it.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Divine', 'Presence', 'Perception'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'mystical',
    tags: ['divine', 'presence', 'perception'],
  },
  {
    persianText: 'فقر، شرافتِ بی‌شرفی است.',
    transliteration: 'Faqr, sharaf-e bi-sharafe jah ast.',
    englishTranslation: 'Poverty is the honor of the honorless world.',
    summary: 'Spiritual poverty is the true honor.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Poverty', 'Honor', 'Spirituality'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['poverty', 'honor', 'spiritual'],
  },
  {
    persianText: 'مَنالِ دل نِی مالِ دل است.',
    transliteration: 'Manal-e jah ni mal-e jah ast.',
    englishTranslation: 'Worldly earnings are not worldly possessions.',
    summary: 'What we gain in the world does not truly belong to us.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['World', 'Possessions', 'Philosophy'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'philosophical',
    tags: ['world', 'possessions', 'wisdom'],
  },
  {
    persianText: 'عشق، همه را ویران کند و قصر سازد.',
    transliteration: 'eshq, hameh ra viran kunad va qasr sazad.',
    englishTranslation: 'Love destroys everything and builds a palace.',
    summary: 'Love breaks down旧的 to build something new.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Love', 'Destruction', 'Building'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'transformative',
    tags: ['love', 'destruction', 'building'],
  },
  {
    persianText: 'دیوارِ مِیخانه، دیوارِ بهشت است.',
    transliteration: 'Divar-e meykhaneh, divar-e behest ast.',
    englishTranslation: 'The wall of the tavern is the wall of paradise.',
    summary: 'Places of spiritual intoxication are paradisiacal.',
    sourceWork: 'Divan-e Hafez',
    philosopher: 'hafez',
    themes: ['Paradise', 'Tavern', 'Spiritual'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'spiritual',
    tags: ['paradise', 'tavern', 'spiritual'],
  },
];

// Additional Saadi verses
const saadiVersesAdditional = [
  {
    persianText: 'کسی که نفسِ خویشتن را بِدست آرد، همه دل را بِدست آورده است.',
    transliteration: 'Kasi ke nafas-e khishtun ra bedast avard, hameh jah ra bedast avordeh ast.',
    englishTranslation: 'One who conquers oneself has conquered the entire world.',
    summary: 'Self-mastery is the greatest achievement.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Self-mastery', 'World', 'Victory'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['self-mastery', 'world', 'victory'],
  },
  {
    persianText: 'نادان، به کسی نَگویَد نادان که تو نادانی.',
    transliteration: 'Nadan, be kasi naguyad nadani ke tu nadan-i.',
    englishTranslation: 'Do not tell anyone you are ignorant, lest they think you are foolish.',
    summary: 'Wisdom includes not advertising one\'s weaknesses.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Wisdom', 'Prudence', 'Self-awareness'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['wisdom', 'prudence', 'self-awareness'],
  },
  {
    persianText: 'با دشمنِ مِهرورز، دوستِ صادق باش.',
    transliteration: 'Ba dushman-e mehrvaraz, dust-e saadiq bash.',
    englishTranslation: 'Be a true friend to those who show love even if they are enemies.',
    summary: 'Respond to love even from enemies.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Friendship', 'Love', 'Generosity'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'generous',
    tags: ['friendship', 'love', 'generosity'],
  },
  {
    persianText: 'سخنِ نیکو، مُهرِ یاقوت است بر انگشتر.',
    transliteration: 'Sokhan-e nigo, mohr-e yaqut ast bar angoshtar.',
    englishTranslation: 'Good words are a ruby seal on a ring.',
    summary: 'Kind words are precious and seal relationships.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Speech', 'Kindness', 'Value'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['speech', 'kindness', 'value'],
  },
  {
    persianText: 'بر درختِ مَیوِه نِیال، مِیوِه چیند.',
    transliteration: 'Bar derakht-e miveh niyal, miveh chin.',
    englishTranslation: 'Do not sit idle on the fruit tree expecting to harvest fruit.',
    summary: 'Effort is required for reward.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Effort', 'Reward', 'Action'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['effort', 'reward', 'action'],
  },
  {
    persianText: 'آن کس که داند و بداند که می‌داند، به بِه= است.',
    transliteration: 'An kas ke danad va bedanad ke midanad, beh jah ast.',
    englishTranslation: 'One who knows and knows they know is truly wise.',
    summary: 'True wisdom includes self-awareness of one\'s knowledge.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Knowledge', 'Wisdom', 'Self-awareness'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['knowledge', 'wisdom', 'self-awareness'],
  },
  {
    persianText: 'سکوت، نشانِ فضلِ دل است.',
    transliteration: 'Sokut, nishan-e fazl-e jah ast.',
    englishTranslation: 'Silence is a sign of the virtue of the great.',
    summary: 'The wise speak less and listen more.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Silence', 'Virtue', 'Wisdom'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['silence', 'virtue', 'wisdom'],
  },
  {
    persianText: 'دوستِ راستین، در روزِ سخت شناخته می‌شود.',
    transliteration: 'Dust-e rastin, dar roz-e sakht shenakhte mishavad.',
    englishTranslation: 'A true friend is known in difficult times.',
    summary: 'Adversity reveals true friends.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Friendship', 'Adversity', 'Loyalty'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['friendship', 'adversity', 'loyalty'],
  },
  {
    persianText: 'خواجه، خواجه می‌شناسَد خواجه را.',
    transliteration: 'Khwajeh, khwajeh mishenasad khwajeh ra.',
    englishTranslation: 'A master recognizes a master.',
    summary: 'Like recognizes like.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Recognition', 'Mastery', 'Wisdom'],
    wisdomScore: 8,
    complexity: 3,
    emotionalTone: 'wise',
    tags: ['recognition', 'mastery', 'wisdom'],
  },
  {
    persianText: 'با کسی مِیال که مِیلِ تو دارد.',
    transliteration: 'Ba kasi miyal ke mil-e to darad.',
    englishTranslation: 'Sit with those who desire your well-being.',
    summary: 'Choose companions who wish you good.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Companionship', 'Well-being', 'Choice'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['companionship', 'wellbeing', 'choice'],
  },
  {
    persianText: 'کَرِ نفس، مُوجِ بَهَرِ دل است.',
    transliteration: 'Karr-e nafas, moj-e bahr-e jah ast.',
    englishTranslation: 'Controlling breath creates waves in the sea of the world.',
    summary: 'Self-control affects the world around us.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Self-control', 'Influence', 'Power'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['self-control', 'influence', 'power'],
  },
  {
    persianText: 'گرچه زرِ ناب، بَر سرِ دل بَر تو، لیکن نفس به بِه= است.',
    transliteration: 'Garche zar-e nab, bar sar-e jah bar to, lekin nafas beh jah ast.',
    englishTranslation: 'Though pure gold is upon your head, a breath (life) is better than the world.',
    summary: 'Life itself is more valuable than all wealth.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Life', 'Value', 'Wealth'],
    wisdomScore: 9,
    complexity: 5,
    emotionalTone: 'wise',
    tags: ['life', 'value', 'wealth'],
  },
  {
    persianText: 'علم به بِه= دل آموزد، ادب به بِه= دل پرورَد.',
    transliteration: 'Elm beh jah amuzad, adab beh jah parvardad.',
    englishTranslation: 'Knowledge teaches; culture nurtures.',
    summary: 'Both education and culture are needed for complete development.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Knowledge', 'Culture', 'Education'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['knowledge', 'culture', 'education'],
  },
  {
    persianText: 'آن کس که بُوَد زَبََر، نِیکُو نِیکُو گوید.',
    transliteration: 'An kas ke bowad zabbar, niku niku guyad.',
    englishTranslation: 'The powerful one speaks kindly.',
    summary: 'True strength includes gentle speech.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Strength', 'Kindness', 'Speech'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['strength', 'kindness', 'speech'],
  },
  {
    persianText: 'نیکُویی، نَردِبانِ بهشت است.',
    transliteration: 'Niku-yi, nardaban-e behest ast.',
    englishTranslation: 'Goodness is the ladder to paradise.',
    summary: 'Virtue leads to spiritual reward.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Goodness', 'Paradise', 'Virtue'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'hopeful',
    tags: ['goodness', 'paradise', 'virtue'],
  },
  {
    persianText: 'صبر، مُفتاحِ هر خیر است.',
    transliteration: 'Sabar, miftah-e har kheir ast.',
    englishTranslation: 'Patience is the key to all good.',
    summary: 'Patience unlocks all blessings.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Patience', 'Good', 'Key'],
    wisdomScore: 9,
    complexity: 3,
    emotionalTone: 'wise',
    tags: ['patience', 'good', 'key'],
  },
  {
    persianText: 'بدی مکن، که به تو بازگردد.',
    transliteration: 'Badi makun, ke be to bazgardad.',
    englishTranslation: 'Do no evil, for it will return to you.',
    summary: 'What you do comes back to you.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Karma', 'Action', 'Consequence'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['karma', 'action', 'consequence'],
  },
  {
    persianText: 'به年终،年终،年终 که دل به بِه= دل بُوَد.',
    transliteration: 'Be akhir, akhir, akhir ke beh jah bowad.',
    englishTranslation: 'In the end, all that matters is what is noble.',
    summary: 'Ultimate success is measured by nobility.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['End', 'Nobility', 'Success'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['end', 'nobility', 'success'],
  },
  {
    persianText: 'آن کس که بی‌گناه، بُوَد زَnexus بی‌گناه به بِه= دل رَوَد.',
    transliteration: 'An kas ke bi-gonah bowad, az gonah bi-gonah be jah ravad.',
    englishTranslation: 'One who is innocent goes from innocence to paradise.',
    summary: 'Innocence leads to spiritual reward.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Innocence', 'Paradise', 'Purity'],
    wisdomScore: 8,
    complexity: 5,
    emotionalTone: 'pure',
    tags: ['innocence', 'paradise', 'purity'],
  },
  {
    persianText: 'مِیلِ دل نِی، مِیلِ دل.',
    transliteration: 'Mil-e jah ni, mil-e jah.',
    englishTranslation: 'Desire for the world is not (true) desire.',
    summary: 'Worldly desires are not true aspirations.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Desire', 'World', 'True desire'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['desire', 'world', 'wisdom'],
  },
  {
    persianText: 'فَضل، فَضل است؛ لیکن، نِیکُویی به بِه= دل است.',
    transliteration: 'Fazl, fazl ast; lekin, niku-yi beh jah ast.',
    englishTranslation: 'Grace is grace; but goodness is better than the world.',
    summary: 'Virtue outweighs all worldly power.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Grace', 'Goodness', 'Virtue'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['grace', 'goodness', 'virtue'],
  },
  {
    persianText: 'به کِی گویَم که من چه کِشَدم؟',
    transliteration: 'Be ki guyam ke man che koshtam?',
    englishTranslation: 'To whom shall I tell what I have suffered?',
    summary: 'The depth of personal suffering is often incommunicable.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Suffering', 'Communication', 'Loneliness'],
    wisdomScore: 8,
    complexity: 4,
    emotionalTone: 'melancholic',
    tags: ['suffering', 'communication', 'loneliness'],
  },
  {
    persianText: 'مَن مِی‌داند که نِی مِی‌داند.',
    transliteration: 'Man mi-danad ke ni mi-danad.',
    englishTranslation: 'I know that I do not know.',
    summary: 'True wisdom begins with knowing our ignorance.',
    sourceWork: 'Gulistan',
    philosopher: 'saadi',
    themes: ['Knowledge', 'Ignorance', 'Wisdom'],
    wisdomScore: 9,
    complexity: 3,
    emotionalTone: 'wise',
    tags: ['knowledge', 'ignorance', 'wisdom'],
  },
  {
    persianText: 'باید که نیکُویی کُنی، اگر نیکُویی بینی.',
    transliteration: 'Bayad ke niku-yi koni, agar niku-yi bini.',
    englishTranslation: 'You must do good, if you wish to see good.',
    summary: 'We attract what we embody.',
    sourceWork: 'Bustan',
    philosopher: 'saadi',
    themes: ['Goodness', 'Action', 'Attraction'],
    wisdomScore: 9,
    complexity: 4,
    emotionalTone: 'wise',
    tags: ['goodness', 'action', 'attraction'],
  },
];

// Works/Chapters data
const works = [
  {
    philosopherId: 'rumi',
    title: 'Masnavi-i Ma\'navi',
    titlePersian: ' مثنوی معنوی',
    description: 'The Spiritual Masnavi - A 25,000 verse mystical epic considered the "Koran in Persian". It weaves together stories, parables, and mystical teachings about divine love, self-knowledge, and spiritual transformation.',
    type: 'epic',
    year: '1258-1273',
    tags: ['Sufism', 'Mysticism', 'Spiritual', 'Love', 'Wisdom'],
    chapters: [
      {
        title: 'The Story of the Reed Flute',
        titlePersian: 'داستان نی',
        content: 'Listen to the reed how it tells a tale, complaining of separations...',
        order: 1,
        summary: 'The famous opening of the Masnavi where Rumi uses the reed flute as a metaphor for the soul\'s longing for the divine.',
      },
      {
        title: 'The Merchant and the Parrot',
        titlePersian: 'داستان تاجر و طوطی',
        content: 'A merchant had a parrot whom he loved dearly...',
        order: 2,
        summary: 'A parable about a parrot who refuses to speak for his master until he sees the master\'s genuine sorrow.',
      },
      {
        title: 'The Elephant in the Dark',
        titlePersian: 'فیل در تاریکی',
        content: 'An elephant was brought to a dark house...',
        order: 3,
        summary: 'A famous parable about blind men examining an elephant - illustrating how partial perspectives create conflict.',
      },
    ],
  },
  {
    philosopherId: 'rumi',
    title: 'Divan-e Shams-e Tabrizi',
    titlePersian: 'دیوان شمس تبریزی',
    description: 'The Divan of Shams of Tabriz - Over 40,000 verses dedicated to Rumi\'s spiritual companion Shams-e Tabrizi, expressing the peak of divine love poetry.',
    type: 'lyrical',
    year: '1240-1273',
    tags: ['Love', 'Passion', 'Divine', 'Sufism'],
    chapters: [
      {
        title: 'Ghazal of the Sun',
        titlePersian: 'غزل آفتاب',
        content: 'Come, come, whoever you are, come...',
        order: 1,
        summary: 'Rumi\'s famous invitation to all seekers.',
      },
    ],
  },
  {
    philosopherId: 'hafez',
    title: 'Divan-e Hafez',
    titlePersian: 'دیوان حافظ',
    description: 'The Complete Divan of Hafez - A collection of ghazals (lyrical poems) exploring divine love, wine, the tavern, and spiritual longing.',
    type: 'lyrical',
    year: '1350-1390',
    tags: ['Love', 'Wine', 'Spiritual', 'Mystical'],
    chapters: [
      {
        title: 'The Cupbearer',
        titlePersian: 'ساقی',
        content: 'Saki, come and fill the cup with wine...',
        order: 1,
        summary: 'The cupbearer motif representing divine blessings.',
      },
    ],
  },
  {
    philosopherId: 'saadi',
    title: 'Gulistan',
    titlePersian: 'گلستان',
    description: 'The Rose Garden - A collection of poems and prose on ethics, wisdom, and proper conduct.',
    type: 'moral',
    year: '1258',
    tags: ['Ethics', 'Wisdom', 'Moral', 'Conduct'],
    chapters: [
      {
        title: 'On the Customs of Kings',
        titlePersian: 'باب اول در اخلاق سلاطین',
        content: 'A king asked a sage for wisdom...',
        order: 1,
        summary: 'Teaching about righteous rule.',
      },
      {
        title: 'On the Benefits of Gratitude',
        titlePersian: 'باب دوم در شکرگزاری',
        content: 'Gratitude is the key to all blessings...',
        order: 2,
        summary: 'The virtue of thankfulness.',
      },
    ],
  },
  {
    philosopherId: 'saadi',
    title: 'Bustan',
    titlePersian: 'بستان',
    description: 'The Orchard - A collection of moral and spiritual poetry.',
    type: 'moral',
    year: '1257',
    tags: ['Moral', 'Spiritual', 'Wisdom'],
    chapters: [
      {
        title: 'On Justice',
        titlePersian: 'باب عدالت',
        content: 'Justice is the foundation of all virtue...',
        order: 1,
        summary: 'The importance of justice in leadership.',
      },
    ],
  },
  {
    philosopherId: 'attar',
    title: 'Conference of the Birds',
    titlePersian: 'مجلس پرندگان',
    description: 'An allegorical poem about the soul\'s journey to God, represented by birds seeking the Simurgh.',
    type: 'epic',
    year: '1177',
    tags: ['Allegory', 'Soul', 'Journey', 'Sufism'],
    chapters: [
      {
        title: 'The Hoopoe\'s Address',
        titlePersian: 'سخن هدهد',
        content: 'The Hoopoe addressed the birds...',
        order: 1,
        summary: 'The Hoopoe calls the birds to embark on the spiritual journey.',
      },
      {
        title: 'The Valley of Search',
        titlePersian: 'دره جستجو',
        content: 'When the birds began their quest...',
        order: 2,
        summary: 'The beginning of the soul\'s journey.',
      },
    ],
  },
];

const rumiInfo = {
  name: 'Jalāl ad-Dīn Muhammad Rūmī',
  born: '1207',
  died: '1273',
  birthplace: 'Balkh (present-day Afghanistan)',
  era: 'Persian poet, Sufi mystic, Islamic scholar',
  majorWorks: ['Masnavi-i Ma\'navi', 'Divan-e Shams-e Tabrizi', 'Fihi Ma Fihi', 'Mawlana Letters'],
  philosophy: 'Sufism, Divine love, Spiritual unity, Whirling dervishes',
  influence: 'One of the most influential poets in world history, inspiration for countless seekers',
};

const themes = [
  { name: 'Love', description: 'Divine and earthly love, the longing for the Beloved', color: '#e91e63' },
  { name: 'Wisdom', description: 'Philosophical insights and spiritual truths', color: '#ffc107' },
  { name: 'Divine', description: 'God, the sacred, and spiritual reality', color: '#9c27b0' },
  { name: 'Self-knowledge', description: 'Understanding the true self', color: '#3f51b5' },
  { name: 'Journey', description: 'The spiritual path and transformation', color: '#009688' },
  { name: 'Friendship', description: 'Bonds between seekers and the divine', color: '#4caf50' },
  { name: 'Peace', description: 'Inner tranquility and surrender', color: '#00bcd4' },
  { name: 'Transformation', description: 'Personal growth and awakening', color: '#ff5722' },
  { name: 'Longing', description: 'The soul\'s yearning for the divine', color: '#f44336' },
  { name: 'Soul', description: 'The essence of being', color: '#673ab7' },
];

const blogPosts = [
  {
    title: 'The Whirling Dervishes: A Dance of Devotion',
    content: `The whirling dervishes of the Mevlevi order represent the soul's journey towards divine love. Through rotation, they embody the planets orbiting the sun, and the spiritual journey of the ego dying to itself to be reborn in the divine.

Rumi founded the Mevlevi order after his encounter with Shams-e Tabrizi. The whirling practice, known as "sema," is a form of meditation that symbolizes the cutting away of all worldly attachments and the embrace of divine presence.

During the ceremony, the dervishes wear distinctive brown robes and tall brown hats called "sikke," representing the tombstone of the ego. As they spin, they recite Rumi's poetry, particularly from the Masnavi.

The sema begins with a verse from the Quran: "From God we come, to God we return." This embodies the Sufi belief in fana—the annihilation of the self in the divine.

For those seeking to understand Rumi's spirituality, watching or practicing the whirling meditation offers a profound glimpse into the heart of Sufi mysticism.`,
    published: true,
  },
  {
    title: 'Understanding Rumi: A Guide for Beginners',
    content: `Rumi's poetry can seem overwhelming at first glance, with its complex metaphors and mystical references. But his core message is surprisingly simple: love is the answer to everything.

Born in 1207 in what is now Afghanistan, Rumi was a respected Islamic scholar until meeting the wandering dervish Shams-e Tabrizi in 1244. This encounter transformed him from a conventional jurist into one of history's greatest mystical poets.

His major works include:

1. The Masnavi - A 25,000-verse spiritual epic considered the "Koran in Persian"
2. The Divan-e Shams - Over 40,000 verses dedicated to his lost beloved Shams
3. Fihi Ma Fihi - Discourses and spiritual teachings
4. The Letters - Correspondence with disciples

Start with short quotes and ghazals. Let the beauty of the words wash over you before analyzing their meaning. Rumi himself said: "Don't grieve. Anything you lose comes round in another form."

The journey into Rumi's poetry is itself a spiritual practice. Take your time. Let him meet you where you are.`,
    published: true,
  },
  {
    title: 'The Fourteen Steps of a Sufi: A Journey Inward',
    content: `In the Sufi tradition, the path toward divine union involves stages of spiritual development. While different orders have varying numbers of stations, Rumi outlines a profound journey of transformation.

The journey begins with **Longing** - the soul's awakening to its true home. This is followed by **Love**, which burns away all that is not essential.

**Renunciation** marks the letting go of worldly attachments, while **Trust** in the divine guide opens the heart. **Patience** and **Gratitude** become constant companions on the path.

The seeker then enters **Fear** (of separation from the Beloved), **Shame** (before divine light), and **Contentment** (with God's will). 

**Unity** emerges as the self dissolves into the divine. Finally, **Annihilation** (fana) and **Permanence** (baqa) represent the paradox of Sufi realization - the ego dies to live eternally in God.

Rumi writes: "Die before you die." This is not about physical death but the killing of the ego, the false self that believes it is separate from the divine.

The path is not linear but cyclical. We return to these stages again and again, each time with deeper understanding. This is the beauty of Sufi practice - it is a lifetime journey of becoming.`,
    published: true,
  },
];

const learningPaths = [
  {
    title: 'Introduction to Rumi',
    description: 'Begin your journey into the mystical world of Rumi. Learn about his life, his poetry, and the spiritual traditions that shaped his work.',
    difficulty: 'beginner',
    estimatedTime: 30,
    lessons: [
      { title: 'Who Was Rumi?', content: 'Jalal ad-Din Muhammad Rumi was born in 1207 in Balkh, Afghanistan. He was a Persian poet, Islamic scholar, and Sufi mystic who founded the Mevlevi order of whirling dervishes.' },
      { title: 'The Masnavi', content: 'The Masnavi is Rumi\'s magnum opus, a 25,000-verse spiritual epic considered the "Koran in Persian." It weaves together stories, parables, and mystical teachings.' },
      { title: 'The Spiritual Path', content: 'Sufism is the mystical dimension of Islam. Rumi\'s path emphasizes divine love, personal transformation, and the annihilation of the ego in union with the Beloved.' },
    ],
  },
  {
    title: 'The Poetry of Divine Love',
    description: 'Explore Rumi\'s beautiful expressions of divine love and the longing of the soul for the Beloved.',
    difficulty: 'intermediate',
    estimatedTime: 45,
    lessons: [
      { title: 'The Nature of Love', content: 'For Rumi, love is not an emotion but the fundamental force of the universe. All love, whether human or divine, points toward the ultimate Love of God.' },
      { title: 'Longing and Ecstasy', content: 'The soul\'s longing for the Divine is depicted as both painful and beautiful. This longing, or "sevdā," drives the spiritual seeker toward union.' },
      { title: 'The Beloved and the Lover', content: 'In Rumi\'s poetry, the relationship between the Beloved (God) and the lover (the soul) is portrayed with intense emotion and poetic beauty.' },
    ],
  },
  {
    title: 'Wisdom for Daily Life',
    description: 'Apply Rumi\'s timeless wisdom to everyday challenges. Find guidance for relationships, work, and spiritual growth.',
    difficulty: 'beginner',
    estimatedTime: 40,
    lessons: [
      { title: 'Transforming Difficulty', content: 'Rumi teaches that difficulties are opportunities for growth. "The wound is where the light enters" - our challenges become our teachers.' },
      { title: 'The Power of Gratitude', content: 'Gratitude opens the heart to divine blessings. Rumi encourages daily reflection on the gifts of life, no matter how small.' },
      { title: 'Living with Purpose', content: 'Every moment is an opportunity to remember God and serve others. Rumi\'s teachings help us find meaning in ordinary activities.' },
    ],
  },
  {
    title: 'Advanced Studies in Sufism',
    description: 'Deep dive into the philosophical and mystical dimensions of Rumi\'s work for advanced students.',
    difficulty: 'advanced',
    estimatedTime: 60,
    lessons: [
      { title: 'The Concept of Wahdat al-Wujud', content: 'Unity of Being - the philosophical foundation of Rumi\'s mysticism. All existence is a manifestation of the Divine.' },
      { title: 'The Spiritual States', content: 'Sufi practitioners pass through various states (hal) including repentance, silence, solitude, and poverty of spirit.' },
      { title: 'The Maqam of the Sufi', content: 'The stations (maqamat) of spiritual development, from initial faith to ultimate union with God.' },
    ],
  },
];

async function seed() {
  console.log('🌱 Starting Rumi database seeding...\n');

  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Promise.all([
      VerseModel.deleteMany({}),
      BlogPostModel.deleteMany({}),
      AnnotationModel.deleteMany({}),
      UserModel.deleteMany({}),
      WorkModel.deleteMany({}),
    ]);
    console.log('🗑️ Cleared existing data');

    // Seed verses
    console.log('📜 Seeding verses...');
    const allVerses = [...rumiVerses, ...hafezVerses, ...saadiVerses, ...attarVerses, ...sanaiVerses, ...hafezVersesAdditional, ...saadiVersesAdditional];
    const createdVerses = await VerseModel.insertMany(allVerses);
    console.log(`   Created ${createdVerses.length} verses`);

    // Generate embeddings and upsert to Pinecone
    console.log('🔮 Generating embeddings for vector search...');
    try {
      const apiKey = process.env.OPENAI_API_KEY;
      const pineconeKey = process.env.PINECONE_API_KEY;
      console.log(`   OpenAI key present: ${!!apiKey}, starts with: ${apiKey?.substring(0, 7)}...`);
      console.log(`   Pinecone key present: ${!!pineconeKey}`);
      
      if (!pineconeKey) {
        console.log(`   ⚠️ Pinecone not configured - skipping vector upsert`);
      } else {
        const vectorBatch = await Promise.all(
          createdVerses.map(async (verse) => {
            const text = `${verse.persianText} ${verse.englishTranslation} ${verse.themes.join(' ')}`;
            const { embedding } = await generateEmbedding(text);
            return {
              id: verse._id.toString(),
              values: embedding,
              metadata: {
                persianText: verse.persianText,
                englishTranslation: verse.englishTranslation,
                sourceWork: verse.sourceWork,
                themes: verse.themes.join(','),
              },
            };
          })
        );
        
        await upsertVectors(vectorBatch);
        console.log(`   Upserted ${vectorBatch.length} vectors to Pinecone`);
      }
    } catch (error: any) {
      console.log(`   ⚠️ Vector embedding skipped: ${error.message || error.toString()}`);
    }

    // Generate sample images for verses (only if not already set)
    console.log('🎨 Generating AI images for verses (sample)...');
    try {
      // First check which verses already have images
      const versesWithImages = await VerseModel.find({ imageUrl: { $exists: true, $ne: '' } }).select('_id');
      const existingImageIds = new Set(versesWithImages.map(v => v._id.toString()));
      
      // Consistent 13th century Persian miniature prompts for Rumi verses
      const samplePrompts = [
        'A wandering Sufi seeker in traditional robes walking through a moonlit desert, stars overhead, distant minaret silhouette, golden light emanating from the horizon - self-knowledge theme',
        'Two mystical figures embracing beneath an ancient cypress tree, divine light streaming down, gold leaf decorations, celestial beings in the background - divine love theme',
        'A whirling dervish in traditional brown robes spinning in a circular motion, extended arms, skirt flowing, surrounded by concentric rings of golden light - spiritual ecstacy',
        'A human heart transformed into a radiant sun, emitting beams of golden light that illuminate the darkness, mystical symbols floating around, infinite depth - inner light theme',
      ];
      
      let imagesGenerated = 0;
      for (let i = 0; i < Math.min(4, createdVerses.length); i++) {
        // Skip if image already exists in database
        if (existingImageIds.has(createdVerses[i]._id.toString())) {
          console.log(`   Skipped verse ${i + 1} (already has image)`);
          continue;
        }
        const imageUrl = await generateImage(samplePrompts[i]);
        await VerseModel.findByIdAndUpdate(createdVerses[i]._id, { imageUrl });
        console.log(`   Generated image for verse ${i + 1}`);
        imagesGenerated++;
      }
      if (imagesGenerated === 0) {
        console.log(`   All verses already have images`);
      }
    } catch (error: any) {
      console.log(`   ⚠️ Image generation skipped: ${error.message || error.toString()}`);
    }

    // Generate sample TTS audio (optional)
    console.log('🔊 Generating sample TTS audio...');
    try {
      for (let i = 0; i < Math.min(3, createdVerses.length); i++) {
        const audioBuffer = await generateSpeech(createdVerses[i].englishTranslation, 'alloy');
        // Store a placeholder - in production you'd upload to storage and save the URL
        await VerseModel.findByIdAndUpdate(createdVerses[i]._id, { 
          audioUrl: `data:audio/mp3;base64,placeholder` 
        });
      }
      console.log(`   Generated sample TTS for ${Math.min(3, createdVerses.length)} verses`);
    } catch (error: any) {
      console.log(`   ⚠️ TTS generation skipped: ${error.message || 'Unknown error'}`);
    }

    // Seed admin user first
    console.log('👤 Creating admin user...');
    const adminUser = await UserModel.create({
      name: 'Rumi Admin',
      email: 'admin@rumi.app',
      role: 'admin',
      image: 'https://api.dicebear.com/7.x/initials/svg?seed=Rumi',
    });
    console.log('   Created admin user (admin@rumi.app)');

    // Seed blog posts
    console.log('📝 Seeding blog posts...');
    const blogsWithUser = blogPosts.map(post => ({
      ...post,
      userId: adminUser._id,
    }));
    const createdBlogs = await BlogPostModel.insertMany(blogsWithUser);
    console.log(`   Created ${createdBlogs.length} blog posts`);

    // Seed works
    console.log('📚 Seeding works and chapters...');
    const createdWorks = await WorkModel.insertMany(works);
    console.log(`   Created ${createdWorks.length} works with chapters`);

    console.log('\n✅ Seeding completed successfully!');
    console.log('\n📊 Summary:');
    console.log(`   - Verses: ${createdVerses.length}`);
    console.log(`   - Blog posts: ${createdBlogs.length}`);
    console.log(`   - Works: ${createdWorks.length}`);
    console.log(`   - Users: 1`);
    console.log(`   - Themes: ${themes.length}`);
    console.log(`   - Learning paths: ${learningPaths.length}`);

  } catch (error) {
    console.error('❌ Seeding failed:', error);
    throw error;
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

// Run if called directly
seed().catch(console.error);
