import mongoose from 'mongoose';

const quotes = [
  { quote_english: "Life is a balance between holding on and letting go.", themes: ["balance", "acceptance", "life", "wisdom"] },
  { quote_english: "The wound is the place where the Light enters you.", themes: ["pain", "healing", "light", "transformation"] },
  { quote_english: "You were born with wings, why prefer to crawl through life?", themes: ["potential", "awakening", "freedom", "ambition"] },
  { quote_english: "Beauty surrounds us, but usually we need to be walking in a garden to know it.", themes: ["beauty", "nature", "awareness", "presence"] },
  { quote_english: "Do not grieve. Anything you lose comes round in another form.", themes: ["loss", "impermanence", "renewal", "acceptance"] },
  { quote_english: "Oh, bird of my soul, fly away now, For I possess a hundred fortified towers.", themes: ["freedom", "soul", "spiritual", "liberation"] },
  { quote_english: "There are a thousand ways to kneel and kiss the ground; there are a thousand ways to go home again.", themes: ["spirituality", "homecoming", "devotion", "journey"] },
  { quote_english: "Everyone has been made for some particular work, and the desire for that work has been put in every heart.", themes: ["purpose", "calling", "work", "destiny"] },
  { quote_english: "And so it is, that both the Devil and the angelic Spirit present us with objects of desire to awaken our power of choice.", themes: ["choice", "free will", "desire", "spiritual"] },
  { quote_english: "It may be that the satisfaction I need depends on my going away, so that when I've gone and come back, I'll find it at home.", themes: ["journey", "satisfaction", "homecoming", "seeking"] },
  { quote_english: "What matters is how quickly you do what your soul directs.", themes: ["action", "soul", "urgency", "authenticity"] },
  { quote_english: "There is a voice that doesn't use words, listen!", themes: ["silence", "inner voice", "intuition", "presence"] },
  { quote_english: "What hurts you, blesses you. Darkness is your candle.", themes: ["pain", "blessing", "darkness", "light"] },
  { quote_english: "Set your life on fire. Seek those who fan your flames.", themes: ["passion", "inspiration", "community", "transformation"] },
  { quote_english: "Whenever they rebuild an old building, they must first of all destroy the old one.", themes: ["renewal", "destruction", "rebirth", "change"] },
  { quote_english: "Grace comes to forgive and then forgive again.", themes: ["forgiveness", "grace", "mercy", "compassion"] },
  { quote_english: "Respond to every call that excites your spirit.", themes: ["calling", "excitement", "spirit", "adventure"] },
  { quote_english: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", themes: ["authenticity", "individuality", "myth", "self"] },
  { quote_english: "You are not one, you are a thousand. Just light your lantern.", themes: ["multiplicity", "potential", "light", "self"] },
  { quote_english: "Conventional opinion is the ruin of our souls.", themes: ["conformity", "individuality", "soul", "wisdom"] },
  { quote_english: "Inside any deep asking is the answering.", themes: ["questions", "answers", "inner wisdom", "seeking"] },
  { quote_english: "Gratitude is the wine for the soul. Go on. Get drunk.", themes: ["gratitude", "joy", "soul", "celebration"] },
  { quote_english: "With every breath, I plant the seeds of devotion. I am a farmer of the heart.", themes: ["devotion", "heart", "practice", "spirituality"] },
  { quote_english: "Anyone who genuinely and consistently, with both hands, looks for something, will find it.", themes: ["seeking", "faith", "persistence", "truth"] },
  { quote_english: "The garden of the world has no limit except in your mind.", themes: ["mind", "perception", "world", "limitlessness"] },
  { quote_english: "What is planted in each person's soul will sprout.", themes: ["soul", "growth", "potential", "planting"] },
  { quote_english: "Wherever you stand, be the Soul of that place.", themes: ["presence", "soul", "place", "awareness"] },
  { quote_english: "Let yourself become living poetry.", themes: ["art", "life", "poetry", "creativity"] },
  { quote_english: "Patience is the key to joy.", themes: ["patience", "joy", "wisdom", "peace"] },
  { quote_english: "If all you can do is crawl, start crawling.", themes: ["perseverance", "action", "beginnings", "courage"] },
  { quote_english: "The moment you accept what troubles you've been given, the door will open.", themes: ["acceptance", "troubles", "opening", "surrender"] },
  { quote_english: "I should be suspicious of what I want.", themes: ["desire", "self-awareness", "wisdom", "caution"] },
  { quote_english: "My soul is from everywhere, I'm sure of that, and I intend to end up there.", themes: ["soul", "origin", "destination", "spirituality"] },
  { quote_english: "Keep silent, because the world of silence is a vast fullness.", themes: ["silence", "stillness", "fullness", "presence"] },
  { quote_english: "When I die, I shall soar with angels, and when I die to the angels, what I shall become you cannot imagine.", themes: ["death", "transformation", "angelic", "becoming"] },
  { quote_english: "I am neither of the East nor of the West, no boundaries exist within my breast.", themes: ["unity", "boundaries", "identity", "spirituality"] },
  { quote_english: "Woman is a ray of God. She is not that earthly beloved: she is creative, not created.", themes: ["woman", "divine", "creativity", "sacred"] },
  { quote_english: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I will meet you there.", themes: ["love", "beyond judgment", "unity", "connection"] },
  { quote_english: "Grief can be the garden of compassion. If you keep your heart open through everything, your pain can become your greatest ally in your life's search for love and wisdom.", themes: ["grief", "compassion", "pain", "wisdom"] },
  { quote_english: "Everything that is made beautiful and fair and lovely is made for the eye of one who sees.", themes: ["beauty", "vision", "perception", "art"] },
  { quote_english: "The world is a mountain, in which your words are echoed back to you.", themes: ["words", "karma", "world", "echo"] },
  { quote_english: "Now is the time to unite the soul and the world. Now is the time to see the sunlight dancing as one with the shadows.", themes: ["unity", "soul", "world", "light"] },
  { quote_english: "Be like a tree and let the dead leaves drop.", themes: ["renewal", "letting go", "growth", "nature"] },
  { quote_english: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", themes: ["communication", "gentleness", "wisdom", "power"] },
  { quote_english: "Let yourself become living poetry.", themes: ["poetry", "life", "art", "creativity"] },
  { quote_english: "When the lips are silent, the heart has a hundred tongues.", themes: ["silence", "heart", "expression", "non-verbal"] },
  { quote_english: "When someone beats a rug, the blows are not against the rug, but against the dust in it.", themes: ["wisdom", "lesson", "hidden", "truth"] },
  { quote_english: "What shall I say, O Muslims, I know not myself. I am neither a Christian, nor a Jew, nor a Zoroastrian, nor a Muslim.", themes: ["identity", "unity", "beyond labels", "self"] },
  { quote_english: "Sunlight fell upon the wall; the wall received a borrowed splendor. Why set your heart on a piece of Earth, O simple one? Seek out the source which shines forever.", themes: ["light", "source", "eternal", "seeking"] },
  { quote_english: "Water, stories, the body, all the things we do, are mediums that hid and show what's hidden.", themes: ["mediums", "hidden", "stories", "body"] },
  { quote_english: "Let silence be the art you practice.", themes: ["silence", "art", "practice", "stillness"] },
  { quote_english: "We carry inside us the wonders we seek outside us.", themes: ["inner world", "wonder", "seeking", "within"] },
  { quote_english: "Sell your cleverness and buy bewilderment. Cleverness is mere opinion. Bewilderment brings intuitive knowledge.", themes: ["wisdom", "knowledge", "intuition", "surrender"] },
  { quote_english: "Looking up gives light, although, at first, it makes you dizzy.", themes: ["light", "looking up", "dizziness", "elevation"] },
  { quote_english: "If light is in your heart, you will find your way home.", themes: ["light", "heart", "home", "guidance"] },
  { quote_english: "Move within, but don't move the way fear makes you move.", themes: ["fear", "movement", "inner", "courage"] },
  { quote_english: "The wealth within you, your essence, is your kingdom.", themes: ["wealth", "essence", "kingdom", "inner"] },
  { quote_english: "Half-heartedness doesn't reach into majesty.", themes: ["wholeheartedness", "majesty", "commitment", "depth"] },
  { quote_english: "Look at the Moon in the sky, not the one in the lake.", themes: ["truth", "illusion", "moon", "perception"] },
  { quote_english: "There is a life-force within your soul, seek that life. There is a gem in the mountain of your body, seek that mine. O traveler, if you are in search of that, don't look outside, look inside yourself and seek that.", themes: ["soul", "gem", "inner treasure", "seeking"] },
  { quote_english: "Seek the path that demands your whole being.", themes: ["path", "whole being", "commitment", "devotion"] },
  { quote_english: "Work. Keep digging your well. Water is there somewhere.", themes: ["work", "perseverance", "water", "well"] },
  { quote_english: "Death has nothing to do with going away. The Sun sets. The Moon sets. But they are not gone.", themes: ["death", "impermanence", "continuity", "nature"] },
  { quote_english: "Either give me more wine or leave me alone.", themes: ["wine", "love", "presence", "passion"] },
  { quote_english: "Your light is more magnificent than sunrise or sunset.", themes: ["light", "beauty", "magnificence", "inner"] },
  { quote_english: "Seek the wisdom that will untie your knot.", themes: ["wisdom", "knots", "freedom", "release"] },
  { quote_english: "When I am silent, I fall into the place where everything is music.", themes: ["silence", "music", "stillness", "inner"] },
  { quote_english: "To praise the Sun is to praise your own eyes.", themes: ["sun", "eyes", "light", "praise"] },
  { quote_english: "Let's rise above this animalistic behavior and be kind to one another.", themes: ["kindness", "behavior", "humanity", "rising"] },
  { quote_english: "Dance until you shatter yourself.", themes: ["dance", "shattering", "ecstasy", "transformation"] },
  { quote_english: "Be empty of worrying. Think of who created thought.", themes: ["worry", "thought", "creation", "stillness"] },
  { quote_english: "Sit, be still and listen.", themes: ["stillness", "listen", "presence", "silence"] },
  { quote_english: "The lion is most handsome when looking for food.", themes: ["lion", "hunting", "purpose", "strength"] },
  { quote_english: "Caught by our own thoughts, we worry about everything.", themes: ["thoughts", "worry", "freedom", "mind"] },
  { quote_english: "Run from what's comfortable. Forget safety. Live where you fear to live. Destroy your reputation. Be notorious. I have tried prudent planning long enough. From now on, I'll be mad.", themes: ["risk", "madness", "comfort", "fame"] },
  { quote_english: "In silence, there is eloquence. Stop weaving and see how the pattern improves.", themes: ["silence", "eloquence", "pattern", "stopping"] },
  { quote_english: "In the blackest of your moments, wait with no fear.", themes: ["darkness", "moments", "waiting", "fearlessness"] },
  { quote_english: "As you start to walk on the way, the way appears.", themes: ["journey", "way", "walking", "path"] },
  { quote_english: "I have seen the king with a face of Glory, He who is the eye and the Sun of heaven, He who is the companion and healer of all beings, He who is the soul and the universe that births souls.", themes: ["king", "glory", "soul", "universe"] },
  { quote_english: "If you are irritated by every rub, how will your mirror be polished?", themes: ["irritation", "polishing", "mirror", "growth"] },
  { quote_english: "What you seek is seeking you.", themes: ["seeking", "finding", "universe", "connection"] },
  { quote_english: "Achieve some perfection yourself, so that you may not fall into sorrow by seeing the perfection in others.", themes: ["perfection", "self", "sorrow", "others"] },
  { quote_english: "Stop acting so small. You are the universe in ecstatic motion.", themes: ["universe", "ecstasy", "motion", "grandeur"] },
  { quote_english: "Do not feel lonely, the entire universe is inside of you.", themes: ["universe", "loneliness", "inner", "connection"] },
  { quote_english: "When you do things from your soul, you feel a river moving in you, a joy.", themes: ["soul", "joy", "river", "movement"] },
  { quote_english: "Don't make yourself miserable with what is to come or not to come.", themes: ["misery", "future", "present", "acceptance"] },
  { quote_english: "Something opens our wings. Something makes boredom and hurt disappear. Someone fills the cup in front of us: We taste only sacredness.", themes: ["wings", "boredom", "sacredness", "cup"] },
  { quote_english: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", themes: ["wisdom", "change", "world", "self"] },
  { quote_english: "Why should I be unhappy? Every parcel of my being is in full bloom.", themes: ["happiness", "bloom", "being", "wholeness"] },
  { quote_english: "Find the sweetness in your own heart, then you may find the sweetness in every heart.", themes: ["sweetness", "heart", "finding", "universal"] },
  { quote_english: "Your depression is connected to your insolence and refusal to praise.", themes: ["depression", "insolence", "praise", "humility"] },
  { quote_english: "That which is false troubles the heart, but truth brings joyous tranquility.", themes: ["truth", "falsehood", "heart", "tranquility"] },
  { quote_english: "There is an invisible strength within us; when it recognizes two opposing objects of desire, it grows stronger.", themes: ["strength", "desire", "opposites", "growth"] },
  { quote_english: "Listen! Clam up your mouth and be silent like an oyster shell, for that tongue of yours is the enemy of the soul, my friend.", themes: ["silence", "tongue", "soul", "enemy"] },
  { quote_english: "If you find the mirror of the heart dull, the rust has not been cleared from its face.", themes: ["mirror", "heart", "rust", "clearing"] },
  { quote_english: "You know the value of every article of merchandise, but if you don't know the value of your own soul, it's all foolishness.", themes: ["soul", "value", "merchandise", "wisdom"] },
  { quote_english: "That which God said to the rose, and caused it to laugh in full-blown beauty, He said to my heart, and made it a hundred times more beautiful.", themes: ["rose", "god", "heart", "beauty"] },
  { quote_english: "You've come to know the fortunate and the inauspicious stars, but you don't know whether you yourself are fortunate or lucky.", themes: ["stars", "fortune", "luck", "self-knowledge"] },
  { quote_english: "Only from the heart can you touch the sky.", themes: ["heart", "sky", "touch", "love"] },
  { quote_english: "I want to sing like the birds sing, not worrying about who hears or what they think.", themes: ["singing", "birds", "freedom", "authenticity"] },
  { quote_english: "There is a candle in your heart, ready to be kindled. There is a void in your soul, ready to be filled. You feel it, don't you?", themes: ["candle", "void", "soul", "kindling"] },
  { quote_english: "I have been a seeker and I still am, but I stopped asking the books and the stars. I started listening to the teaching of my soul.", themes: ["seeking", "soul", "books", "listening"] },
  { quote_english: "Travel brings power and love back into your life.", themes: ["travel", "power", "love", "life"] },
  { quote_english: "I am not this hair, I am not this skin. I am the soul that lives within.", themes: ["soul", "body", "identity", "self"] },
  { quote_english: "If I love myself, I love you. If I love you, I love myself.", themes: ["love", "self", "other", "unity"] },
  { quote_english: "When will you begin that long journey into yourself?", themes: ["journey", "self", "beginning", "introspection"] },
  { quote_english: "The soul has been given its own ears to hear things the mind does not understand.", themes: ["soul", "ears", "mind", "understanding"] },
  { quote_english: "Your heart is the size of an ocean. Go find yourself in its hidden depths.", themes: ["heart", "ocean", "depths", "finding"] },
  { quote_english: "When the world pushes you to your knees, you're in the perfect position to pray.", themes: ["knees", "prayer", "world", "position"] },
  { quote_english: "The whole universe is contained within a single human being—you.", themes: ["universe", "human", "being", "containment"] },
  { quote_english: "By God, when you see your beauty, you will be the idol of yourself.", themes: ["beauty", "god", "idol", "self"] },
  { quote_english: "It's your road and yours alone. Others may walk it with you, but no one can walk it for you.", themes: ["road", "alone", "others", "journey"] },
  { quote_english: "Whatever lifts the corners of your mouth, trust that.", themes: ["joy", "trust", "mouth", "smile"] },
  { quote_english: "You are not a drop in the ocean. You are the entire ocean, in a drop.", themes: ["ocean", "drop", "unity", "self"] },
  { quote_english: "Your heart knows the way. Run in that direction.", themes: ["heart", "way", "direction", "running"] },
  { quote_english: "These pains you feel are messengers. Listen to them.", themes: ["pain", "messengers", "listening", "messages"] },
  { quote_english: "Beg of God the removal of envy, that God may deliver you from externals and bestow upon you an inward occupation, which will absorb you so that your attention is not drawn away.", themes: ["envy", "god", "inward", "attention"] },
  { quote_english: "Plant the love of the holy ones within your spirit; don't give your heart to anything, but the love of those whose hearts are glad.", themes: ["love", "holy", "spirit", "heart"] },
  { quote_english: "This is the essence of all sciences—that you should know who you will be when the Day of Reckoning arrives.", themes: ["essence", "science", "self", "reckoning"] },
  { quote_english: "Close your eyes, fall in love, stay there.", themes: ["eyes", "love", "falling", "staying"] },
  { quote_english: "Reason is powerless in the expression of Love.", themes: ["reason", "love", "powerless", "expression"] },
  { quote_english: "Lovers don't finally meet somewhere. They're in each other all along.", themes: ["lovers", "meeting", "unity", "connection"] },
  { quote_english: "Would you become a pilgrim on the road of love? The first condition is that you make yourself humble as dust and ashes.", themes: ["pilgrim", "love", "humble", "dust"] },
  { quote_english: "Love rests on no foundation. It's an endless ocean, with no beginning or end.", themes: ["love", "ocean", "endless", "beginning"] },
  { quote_english: "In your light, I learn how to love. In your beauty, how to make poems. You dance inside my chest where no one sees you, but sometimes I do, and that sight becomes this art.", themes: ["light", "beauty", "poem", "dance"] },
  { quote_english: "We are born of love; Love is our mother.", themes: ["love", "born", "mother", "origin"] },
  { quote_english: "Let your Teacher be Love itself.", themes: ["teacher", "love", "guidance", "source"] },
  { quote_english: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", themes: ["love", "barriers", "seeking", "self"] },
  { quote_english: "Let yourself be drawn by the stronger pull of that which you truly love.", themes: ["pull", "love", "attraction", "desire"] },
  { quote_english: "The minute I heard my first love story, I started looking for you, not knowing how blind that was. Lovers don't finally meet somewhere. They're in each other all along.", themes: ["love story", "lovers", "meeting", "blindness"] },
  { quote_english: "The garden of love is green without limit and yields many fruits other than sorrow or joy. Love is beyond either condition: without spring, without autumn, it is always fresh.", themes: ["garden", "love", "fruits", "fresh"] },
  { quote_english: "Through Love, all that is bitter will be sweet. Through Love, all that is copper will be gold. Through Love, all dregs will become wine. Through Love, all pain will turn to medicine.", themes: ["love", "transformation", "bitter", "sweet"] },
  { quote_english: "Love will find its way through all languages on its own.", themes: ["love", "language", "way", "universal"] },
  { quote_english: "You left, and I cried tears of blood. My sorrow grows. It's not just that you left. But when you left, my eyes went with you. Now, how will I cry?", themes: ["leaving", "sorrow", "tears", "eyes"] },
  { quote_english: "The Soul calls from within me: 'You, ignorant of the way of Love, set Me free.'", themes: ["soul", "love", "free", "ignorant"] },
  { quote_english: "May these vows and this marriage be blessed.", themes: ["vows", "marriage", "blessing", "union"] },
  { quote_english: "I have no companion but Love, no beginning, no end, no dawn.", themes: ["love", "companion", "beginning", "end"] },
  { quote_english: "The moment I first heard love, I gave up my soul, my heart and my eyes.", themes: ["love", "soul", "heart", "eyes"] },
  { quote_english: "This is love: to fly toward a secret sky, to cause a hundred veils to fall each moment. First to let go of life. Finally, to take a step without feet.", themes: ["love", "flying", "veils", "step"] },
  { quote_english: "The gifts of lovers to one another are, in respect to love, nothing but forms; yet, they testify to invisible love.", themes: ["lovers", "gifts", "forms", "invisible"] },
  { quote_english: "However much I might try to expound or explain Love, when I come to Love itself, I am ashamed of my explanations.", themes: ["love", "explanations", "shame", "inexplicable"] },
  { quote_english: "Wherever you are, and whatever you do, be in love.", themes: ["love", "presence", "action", "being"] },
  { quote_english: "Be drunk with love, for love is all that exists.", themes: ["love", "drunk", "existence", "ecstasy"] },
  { quote_english: "Whatever happens, just keep smiling and lose yourself in love.", themes: ["smile", "love", "loss", "acceptance"] },
  { quote_english: "Laugh as much as you breathe. Love as long as you live.", themes: ["laugh", "breathe", "love", "live"] },
  { quote_english: "Love is the bridge between you and everything.", themes: ["love", "bridge", "connection", "everything"] },
  { quote_english: "Love alone can explain the mysteries of love and lovers.", themes: ["love", "mysteries", "lovers", "explanation"] },
  { quote_english: "May this marriage be full of laughter, our every day in paradise.", themes: ["marriage", "laughter", "paradise", "day"] },
  { quote_english: "The way the Beloved can fit in my heart, two thousand lives could fit in this body of mine. One kernel could contain a thousand bushels, and a hundred worlds pass through the eye of the needle.", themes: ["beloved", "heart", "body", "universe"] }
];

const verses = quotes.map((q) => ({
  persianText: "",
  transliteration: "",
  englishTranslation: q.quote_english,
  summary: `Rumi: ${q.quote_english}`,
  sourceWork: "Rumi Quotes Collection",
  philosopher: "rumi",
  themes: q.themes,
  wisdomScore: 8,
  complexity: 5,
  tags: ['poetry', 'persian-wisdom', 'rumi', 'english', ...q.themes],
  versions: [],
}));

async function seedRumiQuotes() {
  const mongoUri = process.env.MONGO_URI || 'mongodb+srv://haelpers:Atlas15@haelpers-m0.lz3bcwm.mongodb.net/haelpers?retryWrites=true&w=majority';
  
  await mongoose.connect(mongoUri);
  
  const db = mongoose.connection.db;
  if (!db) throw new Error('No database connection');
  
  const collection = db.collection('verses');
  
  const insertResult = await collection.insertMany(verses);
  console.log(`Inserted ${insertResult.insertedCount} Rumi quotes`);
  
  await mongoose.disconnect();
  console.log('Done!');
}

seedRumiQuotes().catch(console.error);
